[package]
name = "clash"
description = "Rule-based proxy client in Rust"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[workspace]
members = ["shadowsocks"]

[dependencies]
clap = { version = "4.5.26", features = ["derive", "env"] }
